version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USERNAME=livrelo
      - POSTGRES_PASSWORD=password
      - JWT_SECRET=12223-12345-1234
      - SALT_ROUNDS=4
      - DATABASE_URL=postgres://caiosantos:@db/livrelo
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: livrelo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: livrelo
      POSTGRES_HOST_AUTH_METHOD: trust 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  postgres_data: